"""autogenerated by genpy from fleet_control/SearchHoleRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SearchHoleRequest(genpy.Message):
  _md5sum = "1352d8f8d313763b11ff5fb1d8be382a"
  _type = "fleet_control/SearchHoleRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string hole_name

"""
  __slots__ = ['hole_name']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hole_name

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SearchHoleRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hole_name is None:
        self.hole_name = ''
    else:
      self.hole_name = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.hole_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hole_name = str[start:end].decode('utf-8')
      else:
        self.hole_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.hole_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hole_name = str[start:end].decode('utf-8')
      else:
        self.hole_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
"""autogenerated by genpy from fleet_control/SearchHoleResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import hole_detection.msg

class SearchHoleResponse(genpy.Message):
  _md5sum = "9a93ce7dac7d7f7b49862226978ebf28"
  _type = "fleet_control/SearchHoleResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """hole_detection/Hole hole


================================================================================
MSG: hole_detection/Hole
bool found
float64 width
geometry_msgs/Point position


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['hole']
  _slot_types = ['hole_detection/Hole']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hole

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SearchHoleResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hole is None:
        self.hole = hole_detection.msg.Hole()
    else:
      self.hole = hole_detection.msg.Hole()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4d.pack(_x.hole.found, _x.hole.width, _x.hole.position.x, _x.hole.position.y, _x.hole.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.hole is None:
        self.hole = hole_detection.msg.Hole()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.hole.found, _x.hole.width, _x.hole.position.x, _x.hole.position.y, _x.hole.position.z,) = _struct_B4d.unpack(str[start:end])
      self.hole.found = bool(self.hole.found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4d.pack(_x.hole.found, _x.hole.width, _x.hole.position.x, _x.hole.position.y, _x.hole.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.hole is None:
        self.hole = hole_detection.msg.Hole()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.hole.found, _x.hole.width, _x.hole.position.x, _x.hole.position.y, _x.hole.position.z,) = _struct_B4d.unpack(str[start:end])
      self.hole.found = bool(self.hole.found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4d = struct.Struct("<B4d")
class SearchHole(object):
  _type          = 'fleet_control/SearchHole'
  _md5sum = '325cb0df236f063238dc714aa855e7b8'
  _request_class  = SearchHoleRequest
  _response_class = SearchHoleResponse
