(cl:defpackage fleet_control-srv
  (:use )
  (:export
   "INSERTTOHOLE"
   "<INSERTTOHOLE-REQUEST>"
   "INSERTTOHOLE-REQUEST"
   "<INSERTTOHOLE-RESPONSE>"
   "INSERTTOHOLE-RESPONSE"
   "SEARCHHOLE"
   "<SEARCHHOLE-REQUEST>"
   "SEARCHHOLE-REQUEST"
   "<SEARCHHOLE-RESPONSE>"
   "SEARCHHOLE-RESPONSE"
   "SWITCH"
   "<SWITCH-REQUEST>"
   "SWITCH-REQUEST"
   "<SWITCH-RESPONSE>"
   "SWITCH-RESPONSE"
   "CHECKSUCCESS"
   "<CHECKSUCCESS-REQUEST>"
   "CHECKSUCCESS-REQUEST"
   "<CHECKSUCCESS-RESPONSE>"
   "CHECKSUCCESS-RESPONSE"
  ))

