/* Auto-generated by genmsg_cpp for file /home/drl-mocap/ros_stacks/drl-youbot/fleet_control/msg/FleetCommand.msg */
#ifndef FLEET_CONTROL_MESSAGE_FLEETCOMMAND_H
#define FLEET_CONTROL_MESSAGE_FLEETCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace fleet_control
{
template <class ContainerAllocator>
struct FleetCommand_ {
  typedef FleetCommand_<ContainerAllocator> Type;

  FleetCommand_()
  : command()
  , data(0.0)
  {
  }

  FleetCommand_(const ContainerAllocator& _alloc)
  : command(_alloc)
  , data(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;

  typedef double _data_type;
  double data;


  typedef boost::shared_ptr< ::fleet_control::FleetCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fleet_control::FleetCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FleetCommand
typedef  ::fleet_control::FleetCommand_<std::allocator<void> > FleetCommand;

typedef boost::shared_ptr< ::fleet_control::FleetCommand> FleetCommandPtr;
typedef boost::shared_ptr< ::fleet_control::FleetCommand const> FleetCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fleet_control::FleetCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fleet_control::FleetCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fleet_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fleet_control::FleetCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fleet_control::FleetCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fleet_control::FleetCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3b0e888571447feef9b2a74d608e4a3a";
  }

  static const char* value(const  ::fleet_control::FleetCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3b0e888571447feeULL;
  static const uint64_t static_value2 = 0xf9b2a74d608e4a3aULL;
};

template<class ContainerAllocator>
struct DataType< ::fleet_control::FleetCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fleet_control/FleetCommand";
  }

  static const char* value(const  ::fleet_control::FleetCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fleet_control::FleetCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string command\n\
float64 data\n\
\n\
";
  }

  static const char* value(const  ::fleet_control::FleetCommand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fleet_control::FleetCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FleetCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fleet_control::FleetCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fleet_control::FleetCommand_<ContainerAllocator> & v) 
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FLEET_CONTROL_MESSAGE_FLEETCOMMAND_H

