"""autogenerated by genpy from fleet_control/VelTwist.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class VelTwist(genpy.Message):
  _md5sum = "95bf03a87f5869f40f57f1412d35d311"
  _type = "fleet_control/VelTwist"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Twist target
std_msgs/Float64 velocity


================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
================================================================================
MSG: std_msgs/Float64
float64 data
"""
  __slots__ = ['target','velocity']
  _slot_types = ['geometry_msgs/Twist','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VelTwist, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.target is None:
        self.target = geometry_msgs.msg.Twist()
      if self.velocity is None:
        self.velocity = std_msgs.msg.Float64()
    else:
      self.target = geometry_msgs.msg.Twist()
      self.velocity = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.target.linear.x, _x.target.linear.y, _x.target.linear.z, _x.target.angular.x, _x.target.angular.y, _x.target.angular.z, _x.velocity.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.target is None:
        self.target = geometry_msgs.msg.Twist()
      if self.velocity is None:
        self.velocity = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.target.linear.x, _x.target.linear.y, _x.target.linear.z, _x.target.angular.x, _x.target.angular.y, _x.target.angular.z, _x.velocity.data,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.target.linear.x, _x.target.linear.y, _x.target.linear.z, _x.target.angular.x, _x.target.angular.y, _x.target.angular.z, _x.velocity.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.target is None:
        self.target = geometry_msgs.msg.Twist()
      if self.velocity is None:
        self.velocity = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.target.linear.x, _x.target.linear.y, _x.target.linear.z, _x.target.angular.x, _x.target.angular.y, _x.target.angular.z, _x.velocity.data,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7d = struct.Struct("<7d")
